import type { Metadata } from "next";
import { Consent } from "@/components/scripts/Consent";
import { GTM } from "@/components/scripts/GTM";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ParentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="relative">
      <head>
        {/* Force light mode — prevents Brave/Samsung Internet/iOS browser dark mode overrides */}
        <meta name="color-scheme" content="light" />
        <meta name="supported-color-schemes" content="light" />

        {/* Google Fonts - Poppins, Share Tech Mono & Caveat (manuscrite) */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Share+Tech+Mono&family=Caveat:wght@500;600;700&display=swap"
          rel="stylesheet"
        />

        {/* jBox CSS - External Resource */}
        <link 
          href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.3.3/dist/jBox.all.min.css" 
          rel="stylesheet" 
        />
        
        {/* Mapbox GL CSS - CDN Fallback */}
        <link 
          href="https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.css" 
          rel="stylesheet" 
        />
        
        <Consent />
      </head>
      <body
        className="font-sans pt-16 pb-0 2xl:pb-16 2xl:pt-24 transition-all duration-300 ease-in-out bg-background"
      >
        <div className="overflow-x-hidden w-full relative">
          {children}
        </div>
        <GTM />
      </body>
    </html>
  );
}
